[package]
name = "mte-blocks"
version = "0.0.1"
edition = "2021"

[dependencies]
cosmwasm-std = "2"

[dev-dependencies]
cw-multi-test = { version = "2", features = ["staking", "stargate", "cosmwasm_2_0"] }
