version: '3'

silent: true

tasks:

  before-commit:
    desc: Run this before committing any changes
    cmds:
      - cmd: cargo clean
      - cmd: rm -rf Cargo.lock
      - cmd: cargo +stable build

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Deletes all compilation artifacts
    cmds:
      - cmd: cargo clean
      - cmd: rm -rf schema

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov:
    desc: Generates code coverage
    cmds:
      - cmd: ./coverage.sh

  fmt:
    desc: Formats the code
    cmds:
      - cmd: cargo +stable fmt

  test:
    desc: Runs all tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Runs all tests in debug mode
    cmds:
      - cmd: cargo +stable nextest run

  testn-out:
    desc: Runs all tests in debug mode
    cmds:
      - cmd: cargo +stable nextest run

  wasm:
    desc: Builds the Wasm binary
    cmds:
      - cmd: cargo build --release --target wasm32-unknown-unknown --lib

  wasm-debug:
    desc: Builds the Wasm binary in debug mode
    cmds:
      - cmd: cargo build --target wasm32-unknown-unknown --lib
