version: '3'

silent: true

tasks:

  before-commit:
    desc: Run this before committing any changes
    cmds:
      - cmd: cargo clean
      - cmd: rm -rf Cargo.lock
      - cmd: cargo +stable build

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  check:
    desc: Checks the Wasm binary of the compiled contract
    cmds:
      - task: wasm
      - cmd: cosmwasm-check ./target/wasm32-unknown-unknown/release/counter.wasm

  clean:
    desc: Deletes all compilation artifacts
    cmds:
      - cmd: cargo clean
      - cmd: rm -rf schema

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy --all-targets

  cov:
    desc: Generates code coverage
    cmds:
      - task: clean
      - cmd: ./coverage.sh

  fmt:
    desc: Formats the code
    cmds:
      - cmd: cargo +stable fmt

  optimize:
    desc: Optimize the size of the smart contract
    cmds:
      - cmd: docker pull cosmwasm/optimizer:0.16.1
      - cmd: docker run --rm -v "$(pwd)":/code --mount type=volume,source="$(basename "$(pwd)")_cache",target=/target --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry cosmwasm/optimizer:0.16.1

  schema:
    desc: Builds the schema
    cmds:
      - cmd: cargo run --bin schema

  test:
    desc: Runs all tests in debug mode
    cmds:
      - cmd: cargo +stable test

  testn:
    desc: Runs all tests in debug mode
    cmds:
      - cmd: cargo +stable nextest run

  wasm:
    desc: Builds the Wasm binary
    cmds:
      - cmd: cargo +1.81.0-x86_64-unknown-linux-gnu build --release --target wasm32-unknown-unknown --lib

  wasm-debug:
    desc: Builds the Wasm binary in debug mode
    cmds:
      - cmd: cargo build --target wasm32-unknown-unknown --lib
